# Generated by Django 5.2.1 on 2025-06-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100)),
                ('text_field', models.TextField()),
                ('integer_field', models.IntegerField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('float_field', models.FloatField()),
                ('boolean_field', models.BooleanField(default=True)),
                ('created_at_dt', models.DateTimeField(auto_now_add=True)),
                ('created_at_date', models.DateField(auto_now_add=True)),
                ('created_at_time', models.TimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
